#!/bin/bash

# script global variables
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m'


# Get partitions
containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 1; done
  return 0
}

# Input partitions
read -p "Enter root partition: " partition_root
read -p "Enter boot partition: " partition_boot
read -p "Enter swap partition: " partition_swap
read -p "Enter hdd partition: " partition_hdd
read -p "Enter /usr/local partition: " partition_usrlocal

# Input username
read -p "Please type your username: " username
read -s -p "Enter new password for ${username}: (input is not visible)" userpw

# Format and mount partitions
echo
echo Mounting created partition onto /mnt
mkfs.ext4 ${partition_root}
mount ${partition_root} /mnt

echo Mounting remaining partitions
if [ "${partition_hdd}" != "" ]; then
	mkdir /mnt/hdd
	mount ${partition_hdd} /mnt/hdd
fi
if [ "${partition_swap}" != "" ]; then
	mkswap ${partition_swap}
	swapon ${partition_swap}
fi
if [ "${partition_usrlocal}" != "" ]; then
	mkdir -p /mnt/usr/local
	mount ${partition_usrlocal} /mnt/usr/local
fi

# Install arch_linux
echo Installing arch linux into /mnt. This may take some time...
pacstrap /mnt base base-devel linux linux-firmware
echo Finished installing arch linux

# Change pacman mirror
cat /etc/pacman.d/mirrorlist > /mnt/etc/pacman.d/mirrorlist

# Generate file that indicates which partitions to mount on boot
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot into installed linux
echo "#!bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m'

partition_root=\"${partition_root}\"
partition_boot=\"${partition_boot}\"
partition_swap=\"${partition_swap}\"
partition_hdd=\"${partition_hdd}\"
partition_usrlocal=\"${partition_usrlocal}\"
username=\"${username}\"
userpw=\"${userpw}\"
" | cat - apply_settings > temp && mv temp apply_settings

chmod +x apply_settings
cp ./apply_settings /mnt
echo
echo Chrooting into /mnt
arch-chroot /mnt /apply_settings
